[package]
name = "strata-bindings"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[features]
default = ["extension-module"]
extension-module = ["pyo3/extension-module"]

[lib]
name = "strata_ext"
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
pyo3.workspace = true
strata-txn = { path = "../txn" }

[dev-dependencies]
tempfile.workspace = true
